name: projectmanagers
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+2

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl:
  cupertino_icons: ^1.0.2
  get: ^4.3.8
  flutter_screenutil: ^5.0.0+2
  flutter_localizations: # Add this line
    sdk: flutter
  cached_network_image:
    git:
      url: https://github.com/Carapacik/flutter_cached_network_image.git
      path: cached_network_image
  flutter_statusbarcolor_ns: ^0.5.0
  flutter_svg: ^2.0.10+1
  image_picker:
  intl_phone_field: ^3.2.0
  file_picker:
  permission_handler: ^11.3.1
  flutter_html: ^3.0.0-beta.2
  dotted_decoration: ^2.0.0
  circular_reveal_animation: ^2.0.1
  syncfusion_flutter_charts: ^25.2.6
  animated_bottom_navigation_bar: ^1.3.3
  shimmer_animation: ^2.1.0+1
  auto_size_text: ^3.0.0
  loading_indicator: ^3.1.1
  url_launcher: ^6.2.6
  simple_connection_checker: ^0.2.1
  dio: ^5.4.3+1
  get_storage: ^2.1.1
  datetime_picker_formfield: ^2.0.1
  http: ^1.2.1
  animate_do: ^3.3.4
  flutter_keyboard_visibility: ^6.0.0
  flutter_emoji: ^2.5.1
  dotted_border: ^2.0.0+3
  animated_tree_view: ^2.2.0
  hijri:
  flutter_launcher_icons: ^0.13.0
  percent_indicator: ^4.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logoeasydocs.jpg"

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Cairo
      fonts:
        - asset: fonts/Cairo-Regular.ttf
    - family: ArbFONTS-DINNextLTArabic
      fonts:
        - asset: fonts/ArbFONTS-DINNextLTArabic-Regular.ttf
    - family: Cairo
      fonts:
        - asset: fonts/Cairo-SemiBold.ttf
    - family: GraphikArabic
      fonts:
        - asset: fonts/Graphik-Arabic-SemiBold.ttf
  assets:
    - assets/
    - assets/Icons/
    - assets/Icon/